version: '3'

services:
  voicevox:
    image: voicevox/voicevox_engine:nvidia-ubuntu20.04-latest
    container_name: voicevox
    ports:
      - "127.0.0.1:50021:50021"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  voicevox_client:
    image: python:3.10
    container_name: voicevox_request
    volumes:
      - ../src/:/app/src
    working_dir: /app
    tty: true